substitutions:
  device_name: bme280-sensor-hub
  friendly_name: 'BME280 Sensor-Hub'

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp8266:
  board: d1_mini
  framework:
    version: recommended

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret esphome_ota_key

wifi:
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback hotspot"
    password: !secret hotspot_password

# Allow provisioning Wi-Fi via serial or web_server
#improv_serial:
# or connect to the fallback ap and get redirected to a web page for wifi credentials
# To have a "next url" for improv serial
web_server:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

external_components:
  source: github://DonKracho/ESPHome-component-BME280-I2C/components@main
  refresh: 0s
  components: [bme280_i2c_wrapper]

# i2c configuration entry
i2c:
  id: bus_id
  sda: D2
  scl: D1
  scan: false

sensor:
  - platform: bme280_i2c_wrapper
    i2c_id: bus_id
    address: 0x76
    altitude: 61.0
    power_pin: D8
    update_interval: 60s
    temperature:
      name: "BME280 Temp"
      id: bme280_temp
      oversampling: 16x
    humidity:
      name: "BME280 Humi"
      id: bme280_humi  
      oversampling: 16x
    pressure:
      name: "Luftdruck abs."
      id: bme280_pres
      oversampling: 16x
    pressure_sealevel:
      name: "Luftdruck NN"
      id: bme280_psea
    dew_point:
      name: "BME280 Taup"
      id: bme280_taup
    humidity_abs:
      name: "BME280 Habs"
      id: bme280_habs
